### ISSUE TITLE
Method 'DeleteAsync' doesn't have implementation

### ISSUE THREAD

**Issue by amarwadi** [akkadotnet/Akka.Persistence.MongoDB#12]
Hello,
I'm trying to implement Akka Persistence using Mongodb and I am getting an error that says "Method 'DeleteAsync' in type 'Akka.Persistence.MongoDb.Snapshot.MongoDbSnapshotStore' from assembly 'Akka.Persistence.MongoDb, Version=1.0.4.1, Culture=neutral, PublicKeyToken=null' does not have an implementation"

Here is my configuration:

var config = ConfigurationFactory.ParseString(@"
            akka {
                persistence {
                  publish-plugin-commands = on
                  snapshot-store {
                        plugin = ""akka.persistence.snapshot-store.mongodb""
                        mongodb {
                          class = ""Akka.Persistence.MongoDb.Snapshot.MongoDbSnapshotStore, Akka.Persistence.MongoDb""
                          connection-string = ""mongodb://user:pass@paulo.mongohq.com:10083/DbName""
                            collection = ""AkkaSnapshotStore""
                        }
                  }
                  journal {
                        plugin = ""akka.persistence.journal.mongodb""
                        mongodb {
                                class = ""Akka.Persistence.MongoDb.Journal.MongoDbJournal, Akka.Persistence.MongoDb""
                                connection-string = ""mongodb://user:pass@paulo.mongohq.com:10083/DbName""
                                collection = ""AkkaEventJournal""
                        }
                  }
                }
            }");

I think i have created an actor system correctly:

https://gist.github.com/amarwadi/a887b26e14b0d42191b7

and am sending a message to a Persistent Actor and I keep getting the following message infinitely

[ERROR][1/2/2016 2:36:36 AM][Thread 0011][akka://example123/user/section-actor] Method 'DeleteAsync' in type 'Akka.Persistence.MongoDb.Snapshot.MongoDbSnapshotStore' from assembly 'Akka.Persistence.MongoDb, Version=1.0.4.1, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Cause: System.TypeLoadException: Method 'DeleteAsync' in type 'Akka.Persistence.MongoDb.Snapshot.MongoDbSnapshotStore' from assembly 'Akka.Persistence.MongoDb, Version=1.0.4.1, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Akka.Persistence.PersistenceExtension.CreatePlugin(String configPath, Func`2 dispatcherSelector)
   at Akka.Persistence.PersistenceExtension.<>c__DisplayClass13_0.<SnapshotStoreFor>b__0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.get_Value()
   at Akka.Persistence.PersistenceExtension.SnapshotStoreFor(String snapshotPluginId)
   at Akka.Persistence.Eventsourced.get_SnapshotStore()
   at Akka.Persistence.Eventsourced.LoadSnapshot(String persistenceId, SnapshotSelectionCriteria criteria, Int64 toSequenceNr)
   at Akka.Persistence.Eventsourced.<RecoveryPending>b__76_0(Receive receive, Object message)
   at Akka.Persistence.Eventsourced.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)

**Comment by Silv3rcircl3** [comment]
@amarwadi I think this method was added in akka 1.0.5, could you downgrade to 1.0.4 for now? 
Will implement this next week.

Cheers

**Comment by amarwadi** [comment]
Hello,
Thanks for the quick update! I will downgrade to 1.0.4 and let you know if I need anything else.
