### ISSUE TITLE
InvalidCastExceptions when recovering legacy data in ToPersistenceRepresentation and ToSelectedSnapshot

### ISSUE THREAD

**Issue by jackowild** [akkadotnet/Akka.Persistence.MongoDB#134]
I believe this was missed when the LegacySerialization flag was added. I am seeing InvalidCastExceptions when trying to recover events with the LegacySerialization flag turned on.

```
2020-05-11 12:14:28.213 +01:00 [Error] Persistence failure when replaying events for persistenceId [EventPollActor]. Last known sequence number [0]
System.InvalidCastException: Unable to cast object of type 'YL.Common.Data.EventsProcessor' to type 'System.Byte[]'.
   at Akka.Persistence.MongoDb.Snapshot.MongoDbSnapshotStore.ToSelectedSnapshot(SnapshotEntry entry) in C:\work\github\Akka.Persistence.MongoDB\src\Akka.Persistence.MongoDb\Snapshot\MongoDbSnapshotStore.cs:line 183
   at MongoDB.Bson.Serialization.Serializers.ProjectingDeserializer`2.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
   at MongoDB.Driver.Core.Operations.CursorBatchDeserializationHelper.DeserializeBatch[TDocument](RawBsonArray batch, IBsonSerializer`1 documentSerializer, MessageEncoderSettings messageEncoderSettings)
   at MongoDB.Driver.Core.Operations.FindCommandOperation`1.CreateCursorBatch(BsonDocument commandResult)
   at MongoDB.Driver.Core.Operations.FindCommandOperation`1.CreateCursor(IChannelSourceHandle channelSource, BsonDocument commandResult)
   at MongoDB.Driver.Core.Operations.FindCommandOperation`1.ExecuteAsync(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.FindOperation`1.ExecuteAsync(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.FindOperation`1.ExecuteAsync(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperationAsync[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperationAsync[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at MongoDB.Driver.IAsyncCursorSourceExtensions.FirstOrDefaultAsync[TDocument](IAsyncCursorSource`1 source, CancellationToken cancellationToken)
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
```

and

```
2020-05-11 12:15:13.518 +01:00 [Error] Persistence failure when replaying events for persistenceId [EndOfDayPollingActor]. Last known sequence number [0]
System.InvalidCastException: Unable to cast object of type 'YL.Domain.SaxoPayments.ActorModel.Domain.EndOfDay.Steps.Messages.Events.FoundNewEndOfDayContentEvent' to type 'System.Byte[]'.
   at Akka.Persistence.MongoDb.Journal.MongoDbJournal.ToPersistenceRepresentation(JournalEntry entry, IActorRef sender) in C:\work\github\Akka.Persistence.MongoDB\src\Akka.Persistence.MongoDb\Journal\MongoDbJournal.cs:line 351
   at Akka.Persistence.MongoDb.Journal.MongoDbJournal.<>c__DisplayClass11_0.<ReplayMessagesAsync>b__4(JournalEntry doc) in C:\work\github\Akka.Persistence.MongoDB\src\Akka.Persistence.MongoDb\Journal\MongoDbJournal.cs:line 142
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Akka.Persistence.MongoDb.Journal.MongoDbJournal.ReplayMessagesAsync(IActorContext context, String persistenceId, Int64 fromSequenceNr, Int64 toSequenceNr, Int64 max, Action`1 recoveryCallback) in C:\work\github\Akka.Persistence.MongoDB\src\Akka.Persistence.MongoDb\Journal\MongoDbJournal.cs:line 140
```

**Comment by Aaronontheweb** [comment]
closed via #135
