### ISSUE TITLE
Error while creating actor instance of type Akka.Persistence.MongoDb.Journal.MongoDbJournal with 0 args: ()

### ISSUE THREAD

**Issue by DEllement** [akkadotnet/Akka.Persistence.MongoDB#149]
Hi Guys, im currently having weird exception using the MongoDB Persistence:
`[ERROR][08/30/2020 17:59:16][Thread 0018][akka://tf-system/system/akka.persistence.journal.mongodb] Error while creating actor instance of type Akka.Persistence.MongoDb.Journal.MongoDbJournal with 0 args: ()
Cause: [akka://tf-system/system/akka.persistence.journal.mongodb#117067778]: Akka.Actor.ActorInitializationException: Exception during creation
 ---> System.TypeLoadException: Error while creating actor instance of type Akka.Persistence.MongoDb.Journal.MongoDbJournal with 0 args: ()
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Akka.Persistence.MongoDb.MongoDbPersistence' threw an exception.
 ---> MongoDB.Bson.BsonSerializationException: There is already a serializer registered for type Object.
   at MongoDB.Bson.Serialization.BsonSerializerRegistry.RegisterSerializer(Type type, IBsonSerializer serializer)
   at MongoDB.Bson.Serialization.BsonSerializer.RegisterSerializer(Type type, IBsonSerializer serializer)
   at Akka.Persistence.MongoDb.MongoDbPersistence..cctor()
   --- End of inner exception stack trace ---
   at Akka.Persistence.MongoDb.MongoDbPersistence.Get(ActorSystem system)
   at Akka.Persistence.MongoDb.Journal.MongoDbJournal..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass117_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)`

any ideas what this could be?

**Comment by Aaronontheweb** [comment]
Ah, this is an issue with MongoDb's auto-registry of discoverable types for persistence running twice by the looks of it - are you starting up multiple `ActorSystem`s inside the same process by any chance? Could you show us your initialization code?

**Comment by DEllement** [comment]
Thanks for replying,

there is only 1 ActorSystem but its injected via DI in other thread.

so i tracked the issue down to an other thread accessing the ActorSystem too fast at boot, some kind of race condition that happen rarely when message from external queue are processed while the system is still booting up even if its a matter of few milliseconds or seconds.

i dont know about the internal of Akka and how it initialize the persistence plugin, but maybe while, the actorsystem boot and is injected, it perform twice the persistence initialization which trigger the serialization Mapping twice.

Anyways i just need to handle the messages after im guaranteed the ActorSystem is ready.

Thanks for answering and for the library.
