### ISSUE TITLE
TypeloadException when creating MongoDbJournal in integration tests

### ISSUE THREAD

**Issue by simonlaroche** [akkadotnet/Akka.Persistence.MongoDB#155]
This error occurs on our CI server when we try to run integration tests for our persistent actors using the MongoDb Journal

The error only started occurring when we added a second test class.

We use xUnit collections to setup a mongodb server and the collection is configured to disable parallelization. 

This issue looks similar to issue #149

`Cause: [akka://test/system/akka.persistence.journal.mongodb#835136109]: Akka.Actor.ActorInitializationException: Exception during creation
 ---> System.TypeLoadException: Error while creating actor instance of type Akka.Persistence.MongoDb.Journal.MongoDbJournal with 0 args: ()
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Akka.Configuration.ConfigurationException: Invalid replay-filter.mode [], supported values [off, repair-by-discard-old, fail, warn]
   at Akka.Persistence.Journal.AsyncWriteJournal..ctor()
   at Akka.Persistence.MongoDb.Journal.MongoDbJournal..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass117_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)`

Hocon persistence configuration in our tests:
`
akka.persistence {
    journal {
        plugin = "akka.persistence.journal.mongodb"
        replay-filter.mode = fail # we have added the replay filter mode after we first saw the issue but it still occurs
        mongodb {
            connection-string = "..."
            auto-initialize = on
        }
    }
    snapshot-store {
        plugin = "akka.persistence.snapshot-store.mongodb"
        mongodb {
            connection-string = "..."
            auto-initialize = on
        }
    }
}
`

**Comment by simonlaroche** [comment]
We fixed this issue by adding a direct reference to the journal type in our hocon

`$@"
                        akka.persistence {{
                            journal {{
                                plugin = ""akka.persistence.journal.mongodb""
                                mongodb {{
                                    class = ""{typeof(MongoDbJournal).AssemblyQualifiedName}""
                                    connection-string = ""{connectionString}""
                                    auto-initialize = on
                                }}
                            }}
                            snapshot-store {{
                                plugin = ""akka.persistence.snapshot-store.mongodb""
                                mongodb {{
                                    class = ""{typeof(MongoDbSnapshotStore).AssemblyQualifiedName}""
                                    connection-string = ""{connectionString("test")}""
                                    auto-initialize = on
                                }}
                            }}
                        }}"`
