### ISSUE TITLE
Should MongoWriteErrors with duplicate key be considered a persistence failure?

### ISSUE THREAD

**Issue by simonlaroche** [akkadotnet/Akka.Persistence.MongoDB#167]
We get some persistence rejections because of duplicate keys in the event journal. 

Log Message: `Rejected to persist event type [SomeEvetTypeEvent] with sequence number [5812] for persistenceId [***] due to [A bulk write operation resulted in one or more errors. E11000 duplicate key error collection: default.akka.EventJournal index: _id_ dup key: { _id: "***_5812" }].
`

Should there errors be considered as failures since there is no way to recover from these errors without restarting the persistent actor?
```

MongoDB.Driver.MongoBulkWriteException`1[Akka.Persistence.MongoDb.Journal.JournalEntry]: A bulk write operation resulted in one or more errors.
  E11000 duplicate key error collection: default.akka.EventJournal index: _id_ dup key: { _id: "***_5812" }
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at Akka.Persistence.MongoDb.Journal.MongoDbJournal.<>c__DisplayClass13_0.<<WriteMessagesAsync>b__0>d.MoveNext()
```

**Comment by Aaronontheweb** [comment]
No, these should be a `WriteRejectedException`  - which means that an individual write was bad.

What was the underlying issue here? Two persistent actors with the same `PersistentId` ?

**Comment by simonlaroche** [comment]
Yes, probably because of a split brain.

It is more a question of comprehension of the difference between Failure and Rejection.

A Failure would for something like a timeout where we do not know if the write was successful and a Rejection would be for something where we know the write was not successful.

Given that definition should exception like Mongo Queue Full and Timeout Acquiring Connection be considered Rejections since they occur on the client before a write is actually attempted?


```
MongoDB.Driver.MongoWaitQueueFullException: The wait queue for acquiring a connection to server localhost:27017 is full.
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionHelper.EnterWaitQueue()
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.GetChannelAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteContext.InitializeAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteContext.CreateAsync(IWriteBinding binding, Boolean retryRequested, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.BulkMixedWriteOperation.ExecuteAsync(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperationAsync[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteWriteOperationAsync[TResult](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionBase`1.ReplaceOneAsync(FilterDefinition`1 filter, TDocument replacement, ReplaceOptions options, Func`3 bulkWriteAsync)
   at Akka.Persistence.MongoDb.Journal.MongoDbJournal.SetHighSequenceId(IList`1 messages)
   at Akka.Persistence.MongoDb.Journal.MongoDbJournal.WriteMessagesAsync(IEnumerable`1 messages)
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
```

```
System.TimeoutException: Timed out waiting for a connection after 120698ms.
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionHelper.EnteredPool(Boolean enteredPool)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.GetChannelAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteContext.InitializeAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteContext.CreateAsync(IWriteBinding binding, Boolean retryRequested, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.BulkMixedWriteOperation.ExecuteAsync(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperationAsync[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteWriteOperationAsync[TResult](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionBase`1.ReplaceOneAsync(FilterDefinition`1 filter, TDocument replacement, ReplaceOptions options, Func`3 bulkWriteAsync)
   at Akka.Persistence.MongoDb.Journal.MongoDbJournal.SetHighSequenceId(IList`1 messages)
   at Akka.Persistence.MongoDb.Journal.MongoDbJournal.WriteMessagesAsync(IEnumerable`1 messages)
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
```

**Comment by Arkatufus** [comment]
No, those should be failure. A failure means that a message failed to be persisted, regardless of the cause. A rejection means that a message was attempted to be persisted, but it broke the defined protocol, so it is rejected from being persisted.
