### ISSUE TITLE
System.MissingFieldException: Field not found: 

### ISSUE THREAD

**Issue by abdomohamed** [akkadotnet/Akka.Persistence.MongoDB#31]
Hey Team,

 I'm facing below exception and this happened after upgrading to Akka 1.3.2 version. Any clue ?

System.MissingFieldException: Field not found: 'Akka.Persistence.SnapshotSelectionCriteria.MaxSequenceNr'.
   at Akka.Persistence.MongoDb.Snapshot.MongoDbSnapshotStore.CreateRangeFilter(String persistenceId, SnapshotSelectionCriteria criteria)
   at Akka.Persistence.MongoDb.Snapshot.MongoDbSnapshotStore.LoadAsync(String persistenceId, SnapshotSelectionCriteria criteria)
   at Akka.Persistence.Snapshot.SnapshotStore.<>c__DisplayClass5_0.<ReceiveSnapshotStore>b__0()
   at Akka.Util.Internal.AtomicState.<CallThrough>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Akka.Util.Internal.AtomicState.<CallThrough>d__7`1.MoveNext()

I'm happy to have a pull request for fixing it, just I need someone to explain why this is happening :)

**Comment by jackowild** [comment]
Hi, Akka.Persistence.MongoDB has not been updated to work with 1.3.2 of Akka.Persistence yet. The work has been done and PR accepted but the core team haven't put the package on nuget yet.

In the meantime, downgrade Akka.Persistence to 1.1.3.32-beta. You can keep the other akka packages at 1.3.2 and it will work.

@Aaronontheweb could we please upload the latest PR to nuget?

**Comment by jackowild** [comment]
@abdomohamed Version 1.3.5 has now been released which should fix this issue. Can you test and close this please?

**Comment by Aaronontheweb** [comment]
This has been resolved.
